//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Core.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductAddon
    {
        public System.Guid OrderProductAddonId { get; set; }
        public Nullable<System.Guid> OrderProductId { get; set; }
        public Nullable<System.Guid> AddonId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsComplimentary { get; set; }
        public Nullable<bool> IsToGo { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Addon Addon { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Status Status { get; set; }
    }
}
