//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Core.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderEvents = new HashSet<OrderEvent>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.OrderPromotions = new HashSet<OrderPromotion>();
        }
    
        public System.Guid OrderId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<System.Guid> TableId { get; set; }
        public Nullable<System.Guid> OrderTypeId { get; set; }
        public string OrderNumber { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PartySize { get; set; }
        public Nullable<bool> SplitBillEvenFlag { get; set; }
        public Nullable<bool> EmailReceiptFlag { get; set; }
        public Nullable<bool> TextReceiptFlag { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<System.DateTime> PaidTime { get; set; }
        public Nullable<decimal> TaxRatePercent { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> TipAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.Guid> OrderStaffId { get; set; }
        public Nullable<System.Guid> ServiceStaffId { get; set; }
        public Nullable<System.Guid> CashierStaffId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsToGo { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User2 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvent> OrderEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotion> OrderPromotions { get; set; }
    }
}
