//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Core.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPromotion
    {
        public System.Guid OrderPromotionId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
