//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Core.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEvent
    {
        public System.Guid OrderEventId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionVi { get; set; }
        public string DescriptionKo { get; set; }
        public string DescriptionEs { get; set; }
        public string DescriptionZh { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
