//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Core.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantCustomization
    {
        public System.Guid RestaurantCustomizationId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<System.Guid> CustomizationId { get; set; }
    
        public virtual Customization Customization { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
