//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Models_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<bool> IsComplementary { get; set; }
        public Nullable<bool> IsTogo { get; set; }
        public string Notes { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
