//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Models_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> PartySize { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<System.DateTime> PaidTime { get; set; }
        public Nullable<decimal> OrderAmout { get; set; }
        public Nullable<decimal> TipAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> OrderStaff { get; set; }
        public Nullable<int> ServiceStaff { get; set; }
        public Nullable<int> CashierStaff { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User2 { get; set; }
        public virtual Table Table { get; set; }
    }
}
