//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Models_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductAddon
    {
        public int OrderProductAddonId { get; set; }
        public Nullable<int> OrderProductId { get; set; }
        public Nullable<int> AddonId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<bool> IsComplimentary { get; set; }
    
        public virtual Addon Addon { get; set; }
        public virtual Status Status { get; set; }
    }
}
