//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Models_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int TableId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Name { get; set; }
        public string VName { get; set; }
        public string Description { get; set; }
        public string VDescription { get; set; }
        public string Shape { get; set; }
        public string Size { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> LocationY { get; set; }
        public Nullable<int> LocationX { get; set; }
        public Nullable<bool> IsForCustomer { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string Status { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
